# 这是一个配置文件范例.
# 所有账户信息为生成, 请填写您的账户信息.
# 查看帮助与详情: https://github.com/embykeeper/embykeeper#安装与使用

# 每天进行 Telegram Bot 签到的时间范围, 等同于命令行 "-c" 参数.
time = "<6:00PM,10:00PM>"

# 每隔几天进行 Emby 保活, 等同于命令行 "-e" 参数.
interval = 3

# 将关键信息发送到第一个 Telegram 账号, 设为 N 以发送到第 N 个.
notifier = true

# 每个 Telegram Bot 签到的最大尝试时间 (秒).
timeout = 120

# 每个 Telegram Bot 签到的最大尝试次数.
retries = 4

# 最大可同时进行的 Telegram Bot 签到.
concurrent = 1

# 计划任务时, 各站点之间签到的随机时间差异 (分钟).
random = 15

# 代理设置, Emby 和 Telegram 均将通过此代理连接, 服务器位于国内时请配置代理并取消注释.
# hostname = "127.0.0.1"
# port = 1080
# scheme = "socks5" # 可选: http / socks5

# 服务设置, 当您需要禁用某些站点时, 请将该段取消注释并修改.
# 该部分内容是根据 Embykeeper 2.4.9 生成的.

# 默认启用站点:
# [service]
# checkiner = ["charon", "embyhub", "jms", "judog", "ljyy", "magic", "peach", "pornemby", "sssq", "temby", "terminus"]
# monitor = ["bgk", "embyhub", "judog", "pornemby", "viper"]
# messager = ["pornemby"]

# 全部可用站点:
# [service]
# checkiner = ["base", "bluesea", "charon", "embyhub", "jms", "jms_iptv", "judog", "ljyy", "magic", "misty", "nebula", "peach", "pornemby", "singularity", "sssq", "temby", "terminus", "test", "zhipian"]
# monitor = ["base", "bgk", "embyhub", "follow", "judog", "misty", "polo", "pornemby", "test", "viper"]
# messager = ["base", "nakonako", "pornemby", "test"]

# Telegram 账号设置, 您可以重复该片段多次以增加多个账号.

[[telegram]]
phone = "+8613432467447"
send = false # 启用该账号的自动水群功能 (谨慎使用)
monitor = false # 启用该账号的自动监控功能 (需要高级账号)

[[telegram]]
phone = "+8618571188439"
send = false # 启用该账号的自动水群功能 (谨慎使用)
monitor = false # 启用该账号的自动监控功能 (需要高级账号)

# Emby 账号设置, 您可以重复该片段多次以增加多个账号.

[[emby]]
url = "https://fox.org/"
username = "ginaholloway"
password = "*ODzNdoG&8"
time = 10 # 模拟观看的时长 (秒)
progress = 1000 # 模拟观看后设置的时间进度 (秒)

[[emby]]
url = "https://allen.com/"
username = "qsherman"
password = "13GsmBB($A"
time = 10 # 模拟观看的时长 (秒)
progress = 1000 # 模拟观看后设置的时间进度 (秒)
