name: Create Windows Installer Script Archive

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

env:
  WIN_SCRIPT_ZIP_NAME: 'windows-installer-script-v2.6.10.zip'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: ${{ env.WIN_SCRIPT_ZIP_NAME }}
        path: 'windows/installer-script'
        exclusions: 'python-* desktop.ini'
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        prerelease: true
        artifacts: ${{ env.WIN_SCRIPT_ZIP_NAME }}
        token: ${{ secrets.GITHUB_TOKEN }}
        bodyFile: '.github/RELEASE_BODY.md'
