name: Create Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

env:
  WIN_SCRIPT_ZIP_NAME: 'embykeeper-win-v2.6.21.zip'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Archive Windows Installer Script Version
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: ${{ env.WIN_SCRIPT_ZIP_NAME }}
        directory: 'windows/installer-script'
        exclusions: 'python-* desktop.ini'
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        draft: true
        artifacts: ${{ env.WIN_SCRIPT_ZIP_NAME }}
        token: ${{ secrets.GITHUB_TOKEN }}
        bodyFile: '.github/RELEASE_BODY.md'
