name: Create Windows Installer Script Archive

on:
  release:
    types: [released]

env:
  ZIP_NAME: 'windows-installer-script-v2.6.9.zip'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: ${{ env.ZIP_NAME }}
        path: 'windows/installer-script'
        exclusions: 'python-* desktop.ini'
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: ${{ env.ZIP_NAME }}
        token: ${{ secrets.GITHUB_TOKEN }}
